project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    page-layout: full
    