project:
  type: website
  output-dir: docs
  resources:
    - images/
website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lecture-notes.qmd
        text: Lecture Notes
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    page-layout: full
    